package ctl
// einride.shipper.v1beta1
// einride/shipper/v1beta1/address.proto
// einride/shipper/v1beta1/custom_item_type.proto
// einride/shipper/v1beta1/custom_item_type_service.proto
// einride/shipper/v1beta1/lane.proto
// einride/shipper/v1beta1/lane_service.proto
// einride/shipper/v1beta1/load_unit.proto
// einride/shipper/v1beta1/line_item.proto
// einride/shipper/v1beta1/line_item_service.proto
// einride/shipper/v1beta1/shipment.proto
// einride/shipper/v1beta1/oatly_shipment_service.proto
// einride/shipper/v1beta1/opening_hours.proto
// einride/shipper/v1beta1/opening_hours_service.proto
// einride/shipper/v1beta1/shipment_attachment.proto
// einride/shipper/v1beta1/shipment_attachment_service.proto
// einride/shipper/v1beta1/shipment_change_proposal.proto
// einride/shipper/v1beta1/shipment_change_proposal_service.proto
// einride/shipper/v1beta1/shipment_changed_event.proto
// einride/shipper/v1beta1/shipment_claim.proto
// einride/shipper/v1beta1/shipment_claim_service.proto
// einride/shipper/v1beta1/shipment_event.proto
// einride/shipper/v1beta1/shipment_event_service.proto
// einride/shipper/v1beta1/shipment_service.proto
// einride/shipper/v1beta1/shipper.proto
// einride/shipper/v1beta1/shipper_service.proto
// einride/shipper/v1beta1/shipper_settings.proto
// einride/shipper/v1beta1/shipper_settings_service.proto
// einride/shipper/v1beta1/shipper_user_settings.proto
// einride/shipper/v1beta1/shipper_user_settings_service.proto
// einride/shipper/v1beta1/site.proto
// einride/shipper/v1beta1/site_charger.proto
// einride/shipper/v1beta1/site_charger_service.proto
// einride/shipper/v1beta1/site_notification_settings.proto
// einride/shipper/v1beta1/site_notification_settings_service.proto
// einride/shipper/v1beta1/site_service.proto
