package ctl
// einride.planner.v1beta1
// einride/planner/v1beta1/default_schedule.proto
// einride/planner/v1beta1/default_schedule_service.proto
// einride/planner/v1beta1/planner_site_settings.proto
// einride/planner/v1beta1/planner_site_settings_service.proto
// einride/planner/v1beta1/schedule_booking.proto
// einride/planner/v1beta1/schedule_booking_service.proto
// einride/planner/v1beta1/shipment_allocation_settings.proto
// einride/planner/v1beta1/shipment_allocation_status.proto
// einride/planner/v1beta1/shipment_allocation_service.proto
// einride/planner/v1beta1/shipment_assignment_source.proto
// einride/planner/v1beta1/task.proto
// einride/planner/v1beta1/transport_installation.proto
// einride/planner/v1beta1/transport_installation_service.proto
// einride/planner/v1beta1/transport_schedule.proto
// einride/planner/v1beta1/transport_schedule_service.proto
// einride/planner/v1beta1/vehicle_plan.proto
// einride/planner/v1beta1/vehicle_task.proto
// einride/planner/v1beta1/vehicle_plan_service.proto
