package ctl
// einride.planning.v1
// einride/planning/v1/allocate_shipments_job.proto
// einride/planning/v1/allocate_shipments_job_execution.proto
// einride/planning/v1/allocate_shipments_service.proto
// einride/planning/v1/reccurrence_rule.proto
// einride/planning/v1/task_type.proto
// einride/planning/v1/schedule.proto
// einride/planning/v1/schedule_booking_spec.proto
// einride/planning/v1/schedule_booking.proto
// einride/planning/v1/schedule_booking_instance.proto
// einride/planning/v1/schedule_booking_service.proto
// einride/planning/v1/schedule_service.proto
// einride/planning/v1/task.proto
// einride/planning/v1/task_changed_event.proto
// einride/planning/v1/task_service.proto
// einride/planning/v1/transport_installation.proto
// einride/planning/v1/transport_installation_service.proto
