package main

import (
	cobra "github.com/spf13/cobra"
	cli "go.einride.tech/protoc-gen-go-cli/cli"
	v1 "go.einride.tech/protoc-gen-go-cli/proto/cmd/examplectl/einride/example/freight/v1"
)

// Code generated by protoc-gen-go-cli. DO NOT EDIT.
// versions:
// 	protoc        v3.17.3

func NewRootCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use: "examplectl",
	}
	cmd.AddCommand(v1.NewFreightServiceCommand("freight"))
	return cmd
}

func NewConfig() *cli.Config {
	return &cli.Config{
		Compiler: cli.CompilerConfig{Hosts: map[string]string{}, DefaultHost: "", Root: "examplectl", GoogleCloudIdentityTokens: true, Main: true},
	}
}
