// Code generated by aip-cli. DO NOT EDIT.
// versions:
// 	protoc        (unknown)
package main

import (
	context "context"
	fmt "fmt"
	aipcli "go.einride.tech/aip-cli/aipcli"
	os "os"
)

func main() {
	ctx := context.Background()
	cmd := NewRootCommand()
	config := NewConfig()
	config.Runtime.AddToFlagSet(cmd.PersistentFlags(), config.Compiler)
	ctx = aipcli.WithConfig(ctx, config)
	if err := cmd.ExecuteContext(ctx); err != nil {
		_, _ = fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
