package gencli

import (
	"fmt"

	"go.einride.tech/protoc-gen-go-cli/cli"
	"google.golang.org/protobuf/compiler/protogen"
)

const generateFilenameSuffix = "_cli.pb.go"

func GenerateFile(gen *protogen.Plugin, file *protogen.File, config cli.CompilerConfig) error {
	g := gen.NewGeneratedFile(file.GeneratedFilenamePrefix+generateFilenameSuffix, file.GoImportPath)
	g.Skip()
	g.P("package ", file.GoPackageName)
	generateGeneratedFileHeader(g, gen)
	for _, service := range file.Services {
		g.Unskip()
		if err := (newServiceCommandCodeGenerator{
			gen:     gen,
			file:    file,
			service: service,
		}.generateCode(g)); err != nil {
			return err
		}
	}
	return nil
}

func generateGeneratedFileHeader(g *protogen.GeneratedFile, gen *protogen.Plugin) {
	g.P()
	g.P("// Code generated by protoc-gen-go-cli. DO NOT EDIT.")
	g.P("// versions:")
	protocVersion := "(unknown)"
	if v := gen.Request.GetCompilerVersion(); v != nil {
		protocVersion = fmt.Sprintf("v%v.%v.%v", v.GetMajor(), v.GetMinor(), v.GetPatch())
		if s := v.GetSuffix(); s != "" {
			protocVersion += "-" + s
		}
	}
	g.P("// \tprotoc        ", protocVersion)
}
